//------------------------------------------------------------------------------
// <auto-generated>
//     Declares the server controls used by AdminDashboard.aspx.
//     If your project already has this designer file, just add the four
//     stat labels (lblStudents, lblLecturers, lblCourses, lblProgCount).
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    public partial class AdminDashboard
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblUserName;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Label lblTopUserName;

        // Live stat cards
        protected global::System.Web.UI.WebControls.Label lblStudents;
        protected global::System.Web.UI.WebControls.Label lblLecturers;
        protected global::System.Web.UI.WebControls.Label lblCourses;
        protected global::System.Web.UI.WebControls.Label lblProgCount;

        protected global::System.Web.UI.WebControls.DropDownList ddlYear;
        protected global::System.Web.UI.WebControls.Button btnViewAll;
    }
}
