//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Manual changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    public partial class FinalResultProcessing
    {
        /// <summary>lblUserName control.</summary>
        protected global::System.Web.UI.WebControls.Label lblUserName;

        /// <summary>btnLogout control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;

        /// <summary>lblTopUserName control.</summary>
        protected global::System.Web.UI.WebControls.Label lblTopUserName;

        /// <summary>lblMessage control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>ddlSemester control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlSemester;

        /// <summary>btnPreview control.</summary>
        protected global::System.Web.UI.WebControls.Button btnPreview;

        /// <summary>pnlResults control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlResults;

        /// <summary>rptOutcomes control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptOutcomes;

        /// <summary>btnCommit control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCommit;
    }
}
