//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    public partial class LecturerAttendance
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblUserName;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::StudentManagementSystem.NotificationBell ucNotificationBell;
        protected global::System.Web.UI.WebControls.Label lblTopUserName;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.DropDownList ddlCourse;
        protected global::System.Web.UI.WebControls.Button btnLoadStudents;
        protected global::System.Web.UI.WebControls.Button btnRefreshWarnings;
        protected global::System.Web.UI.WebControls.DropDownList ddlSemester;
        protected global::System.Web.UI.WebControls.Button btnGenerateSchedule;
        protected global::System.Web.UI.WebControls.Label lblScheduleInfo;
        protected global::System.Web.UI.WebControls.GridView gvSchedule;
        protected global::System.Web.UI.WebControls.TextBox txtDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlSessionType;
        protected global::System.Web.UI.WebControls.GridView gvStudents;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnSendAllWarnings;
        protected global::System.Web.UI.WebControls.GridView gvWarnings;
    }
}
