//------------------------------------------------------------------------------
// <auto-generated> Designer file generated to match LecturerAnnouncements.aspx </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    public partial class LecturerAnnouncements
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblUserName;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Label lblTopUserName;
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMsg;
        protected global::System.Web.UI.WebControls.Literal litMsg;
        protected global::System.Web.UI.WebControls.Label lblHistoryCount;
        protected global::System.Web.UI.WebControls.GridView gvHistory;
        protected global::System.Web.UI.WebControls.DropDownList ddlCourse;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTitle;
        protected global::System.Web.UI.WebControls.TextBox txtMessage;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMessage;
        protected global::System.Web.UI.WebControls.Button btnPost;
        protected global::System.Web.UI.WebControls.Button btnClear;
    }
}
