//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to match the controls in ManageProgrammes.aspx.
//     If you add or remove server controls, regenerate via Visual Studio
//     (right-click the .aspx > "Convert to Web Application") or edit by hand.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    public partial class ManageProgrammes
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblUserName;
        protected global::System.Web.UI.WebControls.Label lblTopUserName;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;

        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMsg;
        protected global::System.Web.UI.WebControls.Literal litMsg;

        protected global::System.Web.UI.WebControls.GridView gvProgrammes;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnClearSearch;

        protected global::System.Web.UI.WebControls.HiddenField hfProgrammeID;
        protected global::System.Web.UI.WebControls.Label lblFormTitle;

        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvName;

        protected global::System.Web.UI.WebControls.TextBox txtCode;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCode;

        protected global::System.Web.UI.WebControls.DropDownList ddlFaculty;

        protected global::System.Web.UI.WebControls.TextBox txtCredits;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCredits;
        protected global::System.Web.UI.WebControls.RangeValidator rngCredits;

        protected global::System.Web.UI.WebControls.TextBox txtDuration;
        protected global::System.Web.UI.WebControls.RangeValidator rngDuration;

        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnClear;
    }
}
