//------------------------------------------------------------------------------
// <auto-generated> Designer file generated to match ManageUsers.aspx </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    public partial class ManageUsers
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblUserName;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Label lblTopUserName;
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMsg;
        protected global::System.Web.UI.WebControls.Literal litMsg;
        protected global::System.Web.UI.WebControls.Panel pnlCred;
        protected global::System.Web.UI.WebControls.Label lblCredRole;
        protected global::System.Web.UI.WebControls.Label lblCredId;
        protected global::System.Web.UI.WebControls.Label lblCredEmail;
        protected global::System.Web.UI.WebControls.Label lblCredPass;
        protected global::System.Web.UI.WebControls.DropDownList ddlRole;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvName;
        protected global::System.Web.UI.WebControls.TextBox txtPersonalEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPEmail;
        protected global::System.Web.UI.WebControls.TextBox txtIc;
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        protected global::System.Web.UI.WebControls.DropDownList ddlProgramme;
        protected global::System.Web.UI.WebControls.TextBox txtIntake;
        protected global::System.Web.UI.WebControls.TextBox txtEmgName;
        protected global::System.Web.UI.WebControls.TextBox txtEmgPhone;
        protected global::System.Web.UI.WebControls.TextBox txtEmgRel;
        protected global::System.Web.UI.WebControls.DropDownList ddlDept;
        protected global::System.Web.UI.WebControls.DropDownList ddlStaffType;
        protected global::System.Web.UI.WebControls.Button btnCreate;
        protected global::System.Web.UI.WebControls.Button btnClearForm;
        protected global::System.Web.UI.WebControls.Label lblUserCount;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterRole;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.GridView gvUsers;
    }
}
