//------------------------------------------------------------------------------
// <auto-generated> Designer file generated to match ManageCourses.aspx </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    public partial class ManageCourses
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Button btnClearSearch;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlLecturer;
        protected global::System.Web.UI.WebControls.DropDownList ddlProgramme;
        protected global::System.Web.UI.WebControls.DropDownList ddlSemester;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMsg;
        protected global::System.Web.UI.WebControls.GridView gvCourses;
        protected global::System.Web.UI.WebControls.HiddenField hfCourseID;
        protected global::System.Web.UI.WebControls.Label lblFormTitle;
        protected global::System.Web.UI.WebControls.Label lblTopUserName;
        protected global::System.Web.UI.WebControls.Label lblUserName;
        protected global::System.Web.UI.WebControls.Literal litMsg;
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCourseCode;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCourseName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCreditHour;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLecturer;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMaxCapacity;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvProgramme;
        protected global::System.Web.UI.WebControls.RangeValidator rngCreditHour;
        protected global::System.Web.UI.WebControls.RangeValidator rngMaxCapacity;
        protected global::System.Web.UI.WebControls.TextBox txtCourseCode;
        protected global::System.Web.UI.WebControls.TextBox txtCourseName;
        protected global::System.Web.UI.WebControls.TextBox txtCreditHour;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.TextBox txtMaxCapacity;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
    }
}
