//------------------------------------------------------------------------------
// <auto-generated> Designer file generated to match RegisterLecturer.aspx </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    public partial class RegisterLecturer
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Button btnRegister;
        protected global::System.Web.UI.WebControls.CompareValidator cvPassword;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMsg;
        protected global::System.Web.UI.WebControls.GridView gvLecturers;
        protected global::System.Web.UI.WebControls.Label lblLecturerCount;
        protected global::System.Web.UI.WebControls.Label lblTopUserName;
        protected global::System.Web.UI.WebControls.Label lblUserName;
        protected global::System.Web.UI.WebControls.Literal litMsg;
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
    }
}
