//------------------------------------------------------------------------------
// <auto-generated> Designer file generated to match StudentNotifications.aspx </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    public partial class StudentNotifications
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblUserName;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Label lblBellBadge;
        protected global::System.Web.UI.WebControls.Label lblTopUserName;
        protected global::System.Web.UI.WebControls.Label lblUnreadCount;
        protected global::System.Web.UI.WebControls.LinkButton btnMarkAll;
        protected global::System.Web.UI.WebControls.Repeater rptNotifs;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
    }
}
