//------------------------------------------------------------------------------
// <auto-generated> Designer file generated to match StudentTranscript.aspx </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    public partial class StudentTranscript
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.GridView gvAttendance;
        protected global::System.Web.UI.WebControls.GridView gvResults;
        protected global::System.Web.UI.WebControls.Label lblTopUserName;
        protected global::System.Web.UI.WebControls.Label lblUserName;
    }
}
