//------------------------------------------------------------------------------
// <auto-generated> Designer file generated to match VerifyOtp.aspx </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    public partial class VerifyOtp
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblMaskedEmail;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertBox;
        protected global::System.Web.UI.WebControls.TextBox txtOtp;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvOtp;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revOtp;
        protected global::System.Web.UI.WebControls.Button btnVerify;
        protected global::System.Web.UI.WebControls.LinkButton btnResend;
    }
}
